#!/usr/bin/env python3
import sys
import sharlex

def read(fileName):
    with open(fileName) as f:
        lines = []
        lines += f.readlines()
        return lines

file_ = read(sys.argv[1])
data = """{}""".format("".join(file_[0:]))
lexed = sharlex.MyLexer()

lexed.input(data)

while True:
    tok = lexed.token()
    if not tok: 
        break
    print(tok)
